# Minimal Supabase config file.
# See https://supabase.com/docs/guides/local-development/config

# Your project ref. This is used to link your local instance to your Supabase project.
# Automatically populated when you run `supabase link`.
project_id = "zwibykqxbgqqramnyhks"

# Configures the local REST endpoint.
[api]
port = 54321
schemas = ["public", "storage", "graphql"] # Schemas exposed to PostgREST
max_rows = 1000

# Configures the local database instance.
[db]
port = 54322
major_version = 15 # Ensure this matches your Supabase project's Postgres version

# Configures the local Supabase Studio.
[studio]
port = 54323

# Configures the local Realtime service.
[realtime]
enabled = true

# Configures the local Auth service.
[auth]
enable_signup = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
# enable_email_autoconfirm = false
# email_provider = "supabase"
# jwt_expiry = 3600 # seconds

# Configures Supabase Edge Functions.
# Learn more at https://supabase.com/docs/guides/functions/local-development
#[functions."*"] # Wildcard applies to all functions
# verify_jwt = true
# import_map = "supabase/functions/import_map.json"
# entrypoint = "" # Optional: Path to function entrypoint
# command = "" # Optional: Custom command to run function

# Configures the local analytics service.
[analytics]
enabled = false
