-- Admin RBAC System Migration
-- Implements role-based access control for admin functionality
-- Following official Supabase RBAC pattern with Auth Hooks

-- Custom types for roles and permissions
CREATE TYPE public.app_role AS ENUM ('admin', 'user');
CREATE TYPE public.app_permission AS ENUM (
  'content.moderate',     -- Manage flagged content
  'premium.manage',       -- Manage premium listings  
  'analytics.view',       -- View admin dashboard and analytics
  'system.manage'         -- System-level admin functions
);

-- User roles table
CREATE TABLE public.user_roles (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id   uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  role      app_role NOT NULL,
  created_at timestamp with time zone DEFAULT NOW() NOT NULL,
  updated_at timestamp with time zone DEFAULT NOW() NOT NULL,
  UNIQUE (user_id, role)
);

COMMENT ON TABLE public.user_roles IS 'Application roles for each user (admin/user)';

-- Role permissions table
CREATE TABLE public.role_permissions (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role         app_role NOT NULL,
  permission   app_permission NOT NULL,
  created_at   timestamp with time zone DEFAULT NOW() NOT NULL,
  UNIQUE (role, permission)
);

COMMENT ON TABLE public.role_permissions IS 'Permissions assigned to each role';

-- Insert default permissions for admin role
INSERT INTO public.role_permissions (role, permission) VALUES
  ('admin', 'content.moderate'),
  ('admin', 'premium.manage'),
  ('admin', 'analytics.view'),
  ('admin', 'system.manage');

-- Insert default permissions for user role (none for now)
-- Users only get basic authenticated access

-- Enable RLS on tables
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;

-- RLS Policies for user_roles
CREATE POLICY "Users can view their own roles" ON public.user_roles
  FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Only service role can manage user roles" ON public.user_roles
  FOR ALL TO service_role
  USING (true);

-- RLS Policies for role_permissions  
CREATE POLICY "Authenticated users can view role permissions" ON public.role_permissions
  FOR SELECT TO authenticated
  USING (true);

CREATE POLICY "Only service role can manage role permissions" ON public.role_permissions
  FOR ALL TO service_role
  USING (true);

-- Auth hook function to inject roles into JWT
CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  claims jsonb;
  user_role public.app_role;
BEGIN
  -- Fetch the user role from user_roles table
  SELECT role INTO user_role 
  FROM public.user_roles 
  WHERE user_id = (event->>'user_id')::uuid
  LIMIT 1; -- Get first role if multiple exist

  claims := event->'claims';

  IF user_role IS NOT NULL THEN
    -- Set the user_role claim in JWT
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
  ELSE
    -- Default to 'user' role if no role assigned
    claims := jsonb_set(claims, '{user_role}', '"user"');
  END IF;

  -- Update the 'claims' object in the original event
  event := jsonb_set(event, '{claims}', claims);

  -- Return the modified event
  RETURN event;
END;
$$;

-- Grant necessary permissions for the auth hook
GRANT USAGE ON SCHEMA public TO supabase_auth_admin;
GRANT EXECUTE ON FUNCTION public.custom_access_token_hook TO supabase_auth_admin;
REVOKE EXECUTE ON FUNCTION public.custom_access_token_hook FROM authenticated, anon, public;

-- Grant permissions for auth admin to read user roles
GRANT ALL ON TABLE public.user_roles TO supabase_auth_admin;
REVOKE ALL ON TABLE public.user_roles FROM authenticated, anon, public;

-- Create RLS policy for auth admin
CREATE POLICY "Allow auth admin to read user roles" ON public.user_roles
  AS PERMISSIVE FOR SELECT
  TO supabase_auth_admin
  USING (true);

-- Authorization function for RLS policies
CREATE OR REPLACE FUNCTION public.authorize(
  requested_permission app_permission
)
RETURNS boolean AS $$
DECLARE
  bind_permissions int;
  user_role public.app_role;
BEGIN
  -- Fetch user role from JWT token
  SELECT (auth.jwt() ->> 'user_role')::public.app_role INTO user_role;

  -- Count matching permissions for the user's role
  SELECT count(*)
  INTO bind_permissions
  FROM public.role_permissions
  WHERE role_permissions.permission = requested_permission
    AND role_permissions.role = user_role;

  RETURN bind_permissions > 0;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = '';

-- Helper function to check if user is admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN (auth.jwt() ->> 'user_role')::public.app_role = 'admin';
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = '';

-- Triggers for updated_at
CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_timestamp_user_roles 
  BEFORE UPDATE ON public.user_roles 
  FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

-- Grant basic permissions
GRANT SELECT ON public.user_roles TO authenticated;
GRANT SELECT ON public.role_permissions TO authenticated; 