-- Historical Analytics Tracking
-- This migration creates a table to store daily analytics snapshots
-- and sets up a cron job to capture the data automatically.

-- 1. Create the table for storing analytics snapshots
CREATE TABLE IF NOT EXISTS public.analytics_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_date DATE NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
  data JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Add index for faster queries on snapshot_date
CREATE INDEX IF NOT EXISTS idx_analytics_snapshots_snapshot_date ON public.analytics_snapshots(snapshot_date);

-- Enable RLS
ALTER TABLE public.analytics_snapshots ENABLE ROW LEVEL SECURITY;

-- Grant access to authenticated users (or admins if more specific roles exist)
-- For simplicity, allowing any authenticated user to read. Adjust as needed.
CREATE POLICY "Allow read access to authenticated users"
  ON public.analytics_snapshots
  FOR SELECT
  USING (auth.role() = 'authenticated');


-- 2. Create a function to capture all analytics data as a single JSONB object
CREATE OR REPLACE FUNCTION capture_daily_analytics_snapshot()
RETURNS jsonb AS $$
DECLARE
  overview_stats jsonb;
  data_freshness_stats jsonb;
  flagged_content_stats jsonb;
  premium_listings_stats jsonb;
  geographic_dist jsonb;
  category_dist jsonb;
  brand_dist jsonb;
  final_snapshot jsonb;
BEGIN
  -- Overview Stats
  SELECT jsonb_build_object(
    'totalShops', (SELECT count(*) FROM public.rental_shops),
    'totalMotorcycles', (SELECT count(*) FROM public.motorcycle_rentals),
    'totalBrands', (SELECT count(*) FROM public.brands),
    'totalCategories', (SELECT count(*) FROM public.categories)
  ) INTO overview_stats;

  -- Data Freshness, Flagged Content, and Premium Listings Stats
  SELECT to_jsonb(s) INTO data_freshness_stats FROM get_data_freshness_stats() s;
  SELECT to_jsonb(s) INTO flagged_content_stats FROM get_flagged_content_stats() s;
  SELECT to_jsonb(s) INTO premium_listings_stats FROM get_premium_dashboard_stats() s;

  -- Distributions
  SELECT jsonb_agg(s) INTO geographic_dist FROM get_geographic_distribution() s;
  SELECT jsonb_agg(s) INTO category_dist FROM get_category_distribution() s;
  SELECT jsonb_agg(s) INTO brand_dist FROM get_brand_distribution() s;

  -- Combine all stats into the final snapshot object
  SELECT jsonb_build_object(
    'overviewStats', overview_stats,
    'dataFreshness', data_freshness_stats,
    'flaggedContent', flagged_content_stats,
    'premiumListings', premium_listings_stats,
    'geographicDistribution', geographic_dist,
    'categoryDistribution', category_dist,
    'brandDistribution', brand_dist
  ) INTO final_snapshot;

  RETURN final_snapshot;
END;
$$ LANGUAGE plpgsql;

-- 3. Create a function to insert the snapshot (for cron job)
CREATE OR REPLACE FUNCTION insert_daily_snapshot()
RETURNS void AS $$
BEGIN
  INSERT INTO public.analytics_snapshots (data)
  SELECT capture_daily_analytics_snapshot();
END;
$$ LANGUAGE plpgsql;

-- 4. Schedule the cron job to run daily at midnight UTC
-- Ensure pg_cron is enabled in your Supabase project
SELECT cron.schedule(
  'daily-analytics-snapshot',
  '0 0 * * *', -- Every day at midnight UTC
  $$
    SELECT insert_daily_snapshot();
  $$
); 